---
title: "4A Group Project"
author: "Line Shi"
date: "21/03/2020"
output: html_document
---

```{r setup, include=FALSE}

# Set up libraries

setwd("C:/Users/line1/Downloads/4A03_Project-master/4A03_Project-master")

library(dplyr)
library(TSA)
library(data.table)
library(forecast)
library(tseries, quietly = T)

```


```{r}

# Set up data set

LE = fread(file = "/Users/line1/Downloads/4A03_Project-master/4A03_Project-master/Lake_Erie.csv")

LEts = ts( LE[,2],start = c(1921,1),end = c(1970,12),frequency = 12)

```



```{r pressure, echo=FALSE}

# Plot the time series

plot(LEts,  ylab = "Lake Erie Level")
plot(LEts，ylab = "Water Level in Tenth Meters", main = "Monthly Lake Erie Water Level")+
points(x=LEts, y = time(LEts), pch = as.vector(season(LEts)))

qqnorm(LEts, pch = 1, frame = FALSE, main = "Original Dataset")
qqline(LEts, col ="orange", lwd = 3)

#The original dataset is light-tailed with an unsteady variation throughout time

```


```{r Transformation}

# Transformation A: Differencing

TrA = diff(LEts)
plot(TrA, ylab = "Differenced Dataset")
qqnorm(TrA, pch = 1, frame = FALSE, main = "Differenced Dataset")
qqline(TrA, col ="orange", lwd = 3)
### Right Skewed


# Transformation B: Log

TrB = log(LEts)
plot(TrB, ylab = "Log Transformed Dataset") #Not helped much
qqnorm(TrB, pch = 1, frame = FALSE, main = "Log Transformed Dataset")
qqline(TrB, col ="blue", lwd = 3)
### left-Skewed

TrB_mod = diff(log(LEts))
plot(TrB_mod, ylab = "DIfferenced Log Transformed Dataset") #Not helped much
qqnorm(TrB_mod, pch = 1, frame = FALSE, main = "Differenced Log Transformed Dataset")
qqline(TrB_mod, col ="blue", lwd = 3)
### right-skewed

# Transformation C: Power
BoxCox.ar(LEts,lambda = seq(1,2,0.1))
###lambda = 1.6
TrC = LEts^1.6
plot(TrC, ylab = "Power Transformed Dataset") #Not helped much
qqnorm(TrC, pch = 1, frame = FALSE, main = "Power Transformed Dataset")
qqline(TrC, col ="green", lwd = 3)
###light tailed

TrC_mod = diff(TrC)
plot(TrC_mod, ylab = "DIfferenced Power Transformed Dataset") #Not helped much
qqnorm(TrC_mod, pch = 1, frame = FALSE, main = "Differenced Power Transformed Dataset")
qqline(TrC_mod, col ="blue", lwd = 3)
### right-skewed


# Transformation D: Percentage
TrD = na.omit((LEts-zlag(LEts))/zlag(LEts))
plot(percent,ylab = "Percentage Transformed Water Level in Tens Meter", xlab = "", main = "Percentage Transformation")
qqnorm(TrD, pch =1, frame = FALSE, main = "% Transformed Dataset")
qqline(TrD, col = "purple", lwd = 3)

```
```{r}

# Comparing Models

plot(x = TrA[-1], y = TrD[-1], ylab = "% change of Monthly Water Level", xlab = "Difference between Original Dataset and %")
cor(TrA[-1],TrD[-1])

shapiro.test(TrA)
shapiro.test(TrC)
shapiro.test(TrD)
###None of the transformation have a normal distribution

plot(x = zlag(TrD), y = TrD, ylab = "% Transformed Water Level", xlab = "Previous Years' Water Level")


### Autocorrelation plots
acf(TrD, main = "Lag1 Power-transformed Series")
pacf(TrD, main = "Lag1 Power-transformed Series")


```

```{r}

#Power Model fitting

### Stationality

TrD_mod = diff(TrD, 12)
acf(TrD_mod)
pacf(TrD_mod)

TrA_mod = diff(LEts,12)
te1 = arima(TrD,order = c(2,1,1),seasonal = list(order = c(1,1,1),period = 12))
te2 = auto.arima(TrD,stationary = TRUE)
te1



```



```{r}

## myMOdel 

training = window(LE_ts,start=c(1921,1), end=c(1960,12))
test = window(LE_ts,start=c(1961,1), end=c(1970,12))
acf(diff(training^1.6,12))
pacf(diff(training^1.6,12))

plot(diff(training^1.6))


test1 = auto.arima( (training^1.6), stepwise = FALSE, approximation = FALSE)
summary(test1)
#acf(residuals(test1))
#pacf(residuals(test1))


mod3 = arima(training^1.6, order = c(2,1,2),seasonal = list(order = c(1,1,1),period = 12))
summary(mod3)

mod4 = arima(training^1.6, order = c(2,1,2),seasonal = list(order = c(2,1,0),period = 12))
mod4h = arima(training, order = c(0,0,0))
masummary(mod4)


mod5 = arima(training^1.6, order = c(1,1,2),seasonal = list(order = c(1,1,2),period = 12))
summary(mod5)


mod6 = arima(training^1.6, order = c(3,1,3),seasonal = list(order = c(0,1,1),period = 12))
summary(mod6)


mod7 = arima(training^1.6, order = c(1,1,3),seasonal = list(order = c(0,1,1),period = 12))
summary(mod7)






pred1 = predict(test1, n.ahead = 120)
pred = pred1$pred^(1/1.6)

summary(pred)
Upper_CI = (pred1$pred + 1.96*pred1$se)^(1/1.6)
Lower_CI = (pred1$pred - 1.96*pred1$se)^(1/1.6)
plot(LEts, main = "Forecast Using Power Transformation")
lines(test,col="orange",lwd = 2)
lines(Upper_CI,col = "lightgrey")
lines(Lower_CI,col = "lightgrey")
lines(pred,col="blue") 



pred3 = predict(mod3, n.ahead = 120)
pred = pred3$pred^(1/1.6)

summary(pred)
Upper_CI3 = (pred3$pred + 1.96*pred3$se)^(1/1.6)
Lower_CI3 = (pred3$pred - 1.96*pred3$se)^(1/1.6)
plot(LEts, main = "Forecast Using Power Transformation")
lines(test,col="orange",lwd = 2)
lines(Upper_CI3,col = "lightgrey")
lines(Lower_CI3,col = "lightgrey")
lines(pred,col="blue") 


pred7 = predict(mod7, n.ahead = 120)
pred = pred7$pred^(1/1.6)

summary(pred)
Upper_CI7 = (pred7$pred + 1.96*pred7$se)^(1/1.6)
Lower_CI7 = (pred7$pred - 1.96*pred7$se)^(1/1.6)
plot(LEts, main = "Forecast Using Power Transformation")
lines(test,col="orange",lwd = 2)
lines(Upper_CI7,col = "lightgrey")
lines(Lower_CI7,col = "lightgrey")
lines(pred,col="blue") 



pred4 = predict(mod4, n.ahead = 120)
pred = pred4$pred^(1/1.6)

summary(pred)
Upper_CI4 = (pred4$pred + 1.96*pred4$se)^(1/1.6)
Lower_CI4 = (pred4$pred - 1.96*pred4$se)^(1/1.6)
plot(LEts, main = "Forecast Using Power Transformation")
lines(test,col="orange",lwd = 2)
lines(Upper_CI4,col = "lightgrey")
lines(Lower_CI4,col = "lightgrey")
lines(pred,col="blue") 

res4 = residuals(mod4)
shapiro.test(res4)

test2 = auto.arima(diff(training,12), stepwise = FALSE, approximation = FALSE)
summary(test2)
acf(residuals(test2))
pacf(residuals(test2))
pred2 = predict(test2, n.ahead = 120)

summary(pred)
Upper_CI = (pred1$pred + 1.96*pred1$se)
Lower_CI = (pred1$pred - 1.96*pred1$se)
plot(training, main = "Forecast Using Power Transformation")+
lines(test,col="orange",lwd = 2)
lines(Upper_CI,col = "purple")
lines(Lower_CI,col = "purple")
points(pred,col="blue", pch = 19) 
```